### PR TITLE
Task/sapnamysore/tlt 2279/fix labels

### PR DESCRIPTION
**Pull request by sapnamysore**
Fixed the course instructor label and formatting and also fixed unit tests due to this change

### CODE REVIEW

**Comment by elliottyates** [comment]
Can't really verify ACs right now, but code looks good! 👍  :)

**Comment by sapnamysore** [comment]
:-). Shall I merge now, as the ACs are pretty straightforward to spot check once JIRA is back

**Comment by elliottyates** [comment]
Yes please, go for it!

**Comment by elliottyates** [comment]
(test comment, please ignore)

**Pull request merged**
